//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascada_Drop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjunto_Correo
    {
        public int ID { get; set; }
        public Nullable<int> Correo_ID { get; set; }
        public string URL { get; set; }
    
        public virtual Proceso_Correo Proceso_Correo { get; set; }
    }
}
