//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascada_Drop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso_Correo
    {
        public Proceso_Correo()
        {
            this.Adjunto_Correo = new HashSet<Adjunto_Correo>();
        }
    
        public int ID { get; set; }
        public string Asunto { get; set; }
        public string Campo { get; set; }
    
        public virtual ICollection<Adjunto_Correo> Adjunto_Correo { get; set; }
    }
}
